LICENSE
README.md
src/stac_utils/http.py
src/stac_utils/ticker_request.py

allows someone using the stac library to send information to the ticker

TickerRequests

---

src/stac_utils/google.py

instead, the error should very much blow things up

don't pass if error getting service account

---

pyproject.toml
setup.cfg
src/stac_utils/browser/__init__.py
src/stac_utils/browser/downloader.py
src/stac_utils/browser/driver.py

Selenium chrome driver with some presets. 
@jrose-stac can you check whether I did the pre reqs correctly? Or how do we configure it to make it an optional prereq? I'm aware it added a lot of weight to typical installs that won't need any of it.

Browser utilities

---

src/stac_utils/google.py

want it to find the correct service account not get confused and throw an error here

handle no service account found correctly

---

.gitignore
src/stac_utils/google.py

also reorganizes google.py a bit so things are grouped together intuitively

Sheets authentication

---

src/stac_utils/browser/driver.py

Merging in changes from ND polling location deploy

Refactor Chrome Driver to be suitable for lambda

---

src/stac_utils/google.py
src/stac_utils/pandas_utils.py

allows reading and writing with google sheets
for @JulieGoldberg: i pulled one of these out of the polling locations script, you may wish to update the PR after this is merged

sheets read & write

---

src/stac_utils/__init__.py
src/stac_utils/truthy.py
src/tests/test_base_utils.py

utility function mainly intended for env variables (which are always strings) to test for "true" string values.

truthy utility for environment variables

---

src/stac_utils/google.py

add drive to scope so can connect sheets-bq tables

---

src/stac_utils/__init__.py
src/stac_utils/aws.py
src/stac_utils/secret_factory.py
src/tests/test_secret_factory.py

Allows someone, such as a technologist, to build a local `secrets-sp.json` file via input prompts in terminal.

Secrets JSON build

---

src/stac_utils/google.py

This allows creating a whole new table from a dataframe.

Election results

---

setup.cfg

all i've done is specify a version for google-cloud-bigquery in setup.cfg to avoid DistributionNotFound errors

Bq error fix for now

---

setup.cfg

heartbreaking: they released a new version right after i merged the previous PR

---

setup.cfg

use release version of webdriver-manager

---

.circleci/config.yml
requirements.txt
src/stac_utils/email.py
src/tests/test_email.py
src/tests/test_http.py

This is actually @ffaristocrat’s code, but I used it for the Dolly PR and it worked great, so consider it reviewed with approval by me I guess?

allow mailgun template

---

requirements.txt
src/stac_utils/time.py
src/tests/test_time.py

nothing too outré; purpose is to support hourly runs of dolly

get current time

---

src/stac_utils/google.py

for 500 Internal Server Errors

Use Google's internal retry backoff

---

src/stac_utils/google.py

this will enable doing parameterized queries

Job config for run query

---

src/stac_utils/ngpvan.py

Found more problems, should work now for getting saved lists anyway

Pagination

---

src/stac_utils/ngpvan.py

i guess next_page_link inconsistently shows up

Pagination final final fix v2 reboot

---

.circleci/config.yml
src/stac_utils/aws.py
src/stac_utils/benchmark.py
src/stac_utils/convert.py
src/stac_utils/google.py
src/stac_utils/http.py
src/stac_utils/ngpvan.py
src/stac_utils/pandas_utils.py
src/stac_utils/secret_context.py
src/stac_utils/secret_factory.py
src/stac_utils/ticker_request.py
src/stac_utils/time.py
src/tests/browser/test_downloader.py
src/tests/test_aws.py
src/tests/test_benchmark.py
src/tests/test_email.py
src/tests/test_http.py
src/tests/test_ngpvan.py
src/tests/test_pandas_utils.py
src/tests/test_ticker_request.py
src/tests/test_time.py

Outside of formatting & type hints, the only minor changes to the actual code were in time, http and ticker, mainly to make testing easier. http has a bug fix found while writing tests.

Review + Tests

---

.github/workflows/documentation.yml
docs/conf.py
src/stac_utils/email.py

ammaraskar/sphinx-action@master turned out to have an incredibly ancient docker image for sphinx. by forking our own at https://github.com/stac-labs/sphinx-action and upgrading the docker image this magically worked. go figure.
see https://stac-labs.github.io/stac-utils-python/index.html for the live website!

Sphinx tweak

---

src/stac_utils/google.py
src/tests/test_google.py

Fix kwargs passed to build

---

src/stac_utils/pandas_utils.py

- [ x] I have added docstrings to my additions if needed
- [ x] I have added the module to docs/index.rst if it is completely new

add on_bad_lines to panads read_csv

---

src/stac_utils/google.py

- [x ] I have added docstrings to my additions if needed
- [ x] I have added the module to docs/index.rst if it is completely new

importing NotFound exception

---

src/stac_utils/email.py
src/tests/test_email.py

Allows for sending an email using a [Google app password](https://support.google.com/mail/answer/185833?sjid=17597587988540694278-NA). Should generally recommend that people only do this if they are prepared to set up a junk email account that is not their personal, for security reasons. Also Advanced Protection cannot be on.

emailer using smtp and google app password

---

requirements.txt

As above. Tests all pass with a few deprecation warnings that do not appear new.

Fix pandas version to 2.2.1

---

src/stac_utils/aws.py
src/stac_utils/secret_context.py
src/tests/test_aws.py
src/tests/test_secret_context.py

Nested secrets & S3 secret loading

---

.gitignore
requirements.txt
src/stac_utils/google.py
src/tests/test_secret_context.py

Please let me know how this looks to you. It seems to work in the terminal. I can add tests too. 
- [X ] I have added docstrings to my additions if needed

Upload gsheet

---

src/stac_utils/browser/driver.py

Some tweaks to make the browser driver more fooled

Browser tricks

---

src/stac_utils/google.py

Keep in line with other methods to allow for standard credential resolution

Switch upload_file_to_drive to use auth_drive
